"""initial_voting_core_tables

Revision ID: 15533011651c
Revises: 
Create Date: 2026-09-28 20:25:59.452009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15533011651c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('VOTER', 'ADMIN', name='userrole'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('elections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='electionstatus'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elections_status'), 'elections', ['status'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.create_table('eligible_voters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'email', name='uq_election_eligible_email')
    )
    op.create_index(op.f('ix_eligible_voters_election_id'), 'eligible_voters', ['election_id'], unique=False)
    op.create_table('voter_participations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'user_id', name='uq_user_election_vote')
    )
    op.create_index(op.f('ix_voter_participations_election_id'), 'voter_participations', ['election_id'], unique=False)
    op.create_index(op.f('ix_voter_participations_user_id'), 'voter_participations', ['user_id'], unique=False)
    op.create_table('ballots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('election_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ballots_candidate_id'), 'ballots', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_ballots_election_id'), 'ballots', ['election_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ballots_election_id'), table_name='ballots')
    op.drop_index(op.f('ix_ballots_candidate_id'), table_name='ballots')
    op.drop_table('ballots')
    op.drop_index(op.f('ix_voter_participations_user_id'), table_name='voter_participations')
    op.drop_index(op.f('ix_voter_participations_election_id'), table_name='voter_participations')
    op.drop_table('voter_participations')
    op.drop_index(op.f('ix_eligible_voters_election_id'), table_name='eligible_voters')
    op.drop_table('eligible_voters')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_elections_status'), table_name='elections')
    op.drop_table('elections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
